### ISSUE TITLE
Failure to build on arm with gcc 8.3.0

### ISSUE THREAD

**Issue by riban-bw** [gbevin/ShowMIDI#13]
Attempts to build on a Raspberrry Pi running Debian Bullseye armv71 (32-bit) fails with the error:

```
/usr/include/c++/8/bits/unique_ptr.h:79:16: error: invalid application of ‘sizeof’ to incomplete type ‘showmidi::MainLayoutComponent::Pimpl’
  static_assert(sizeof(_Tp)>0,
```
This is during an attempt to build the standalone or the LV2 plugin:
```
make Standalone
make LV2
```
I will also test on 64-bit Bookworm...

**Comment by gbevin** [comment]
Is that the only error, is there more for additional context?

**Comment by riban-bw** [comment]
Full context of error:
```
Compiling PluginEditor.cpp
In file included from /usr/include/c++/8/condition_variable:43,
                 from ../../JUCE/modules/juce_core/system/juce_StandardHeader.h:54,
                 from ../../JUCE/modules/juce_core/juce_core.h:204,
                 from ../../JUCE/modules/juce_audio_basics/juce_audio_basics.h:54,
                 from ../../JuceLibraryCode/JuceHeader.h:17,
                 from ../../Source/PluginEditor.h:20,
                 from ../../Source/PluginEditor.cpp:18:
/usr/include/c++/8/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = showmidi::MainLayoutComponent::Pimpl]’:
/usr/include/c++/8/bits/unique_ptr.h:274:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = showmidi::MainLayoutComponent::Pimpl; _Dp = std::default_delete<showmidi::MainLayoutComponent::Pimpl>]’
../../Source/MainLayoutComponent.h:48:49:   required from here
/usr/include/c++/8/bits/unique_ptr.h:79:16: error: invalid application of ‘sizeof’ to incomplete type ‘showmidi::MainLayoutComponent::Pimpl’
  static_assert(sizeof(_Tp)>0,
                ^~~~~~~~~~~
make: *** [Makefile:329: build/intermediate/Release/PluginEditor_94d4fb09.o] Error 1
```

**Comment by riban-bw** [comment]
Same error on arm 64 bit.

**Comment by gbevin** [comment]
Oh, I'm not surprised this doesn't build on a 32-bit OS

**Comment by gbevin** [comment]
Also this expects C++14 compatibility at least, if the compiler isn't capable of that, it'll not work

**Comment by gbevin** [comment]
I just built it on a Debian 11 aarch64 machine without any issue, all packages updated. 

```
lscpu
Architecture:                       aarch64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
CPU(s):                             2
On-line CPU(s) list:                0,1
Thread(s) per core:                 1
Core(s) per socket:                 2
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          ARM
Model:                              1
Model name:                         Neoverse-N1
```

```
gcc --version
gcc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by gbevin** [comment]
I reworked component instantiation, since it seems that's where your compiler was getting confused. It still builds on all the machines I'm testing on, include that arm machine that passed before too. Would be worth a shot to try that on your system.

**Comment by gbevin** [comment]
Ok, I managed to reproduce your error by installing Debian 10, which has gcc 8.3.0. My latest commit does fix the build and everything succeeds. Closing the issue.

**Comment by riban-bw** [comment]
Thanks for a quick response. There are several warnings during compilation with gcc 8 but they relate to changes in parameter passing since gcc 7 - certainly not worth investigating as they go away with later versions of gcc. I am really pleased that you have fixed this for the older compiler as it means we can use it now in Zynthian and not wait for the (fairly imminent) update to 64-bit Debian 12. I am sharing the news on the [Zynthian forum](https://discourse.zynthian.org/t/midi-news). Cheers!
